import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { Session } from 'next-auth';
import { ReactNode } from 'react';

import NextAuthSessionProvider from './providers/NextAuthSessionProvider';
import QueryProvider from './providers/QueryProvider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  session: Session;
  children: ReactNode;
}

export default function RootLayout({ session, children }: Readonly<RootLayoutProps>) {
  return (
    <html lang={'en'}>
      <NextAuthSessionProvider session={session}>
        <QueryProvider>
          <body className={`${geistSans.variable}  antialiased`}>{children}</body>
        </QueryProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
